[build]
  command = "npm run dev"
  functions = "lambda"  # Jika Anda menggunakan fungsi serverless (Netlify Functions)
   NODE_ENV = "production"
  PATH = "./node_modules/.bin:${PATH}"

[dev]
  command = "npm run dev"
  functions = "lambda"  # Jika Anda menggunakan fungsi serverless (Netlify Functions)
